### ISSUE TITLE
Module not found at "from model import make_model"

### ISSUE THREAD

**Issue by SewoongLee** [ffohturk/CarryingTransformers#1]
I am deeply impressed with your research and grateful for your interesting work.

I am trying to replicate your experiment, but could you possibly enhance the reproducibility a bit more?

For instance, in the DataAnalysis_DecoderOnly.ipynb file, there is an error in the part `from model import make_model`, leading to an unrunnable version of the code.

I would greatly appreciate it if you could share the most recent version of the notebook that you have run, along with a frozen pip requirement environment.

**Comment by ffohturk** [comment]
Hi! Thanks for the interest, I forgot to upload some files for the decoder part, but did so now. Hopefully it works now :)
